stocks = ['AAPL', 'MSFT', 'GOOG', 'AMZN', 'BRK-A', 'TSLA', 'NVDA', 'UNH', 'V', 'XOM', 'META',
        'JNJ', 'JPM', 'WMT', 'MA', 'PG', 'HD', 'CVX', 'LLY', 'BAC', 'MRK', 'BABA', 'ABBV',
        'KO', 'AVGO', 'PEP', 'PFE', 'ORCL', 'COST', 'TMO', 'CSCO', 'MCD', 'NKE', 'DIS',
        'BF-A', 'MOG-A', 'LGF-A', 'DHR', 'ABT', 'ACN', 'TMUS', 'WFC', 'VZ', 'MS',
        'CRM', 'CMCSA', 'ADBE', 'LIN', 'TXN', 'UPS', 'PM', 'NFLX', 'NEE', 'SCHW',
        'BMY', 'RTX', 'QCOM', 'T', 'HON', 'AXP', 'DE', 'CAT', 'LOW', 'AMGN', 'COP', 'BA',
        'AMD', 'GS', 'UNP', 'SBUX', 'IBM', 'LMT', 'PDD', 'ELV', 'SPGI', 'INTC', 'CVS',
        'INTU', 'MDT', 'BX', 'BLK', 'GILD', 'SYK', 'C', 'ADI', 'AMAT', 'BKNG', 'ADP',
        'TJX', 'CI', 'MDLZ', 'GE', 'EL', 'NOW', 'CB', 'MO', 'PYPL', 'ISRG', 'ABNB', 'PGR',
        'MMC', 'REGN', 'TGT', 'ZTS', 'DUK', 'SLB', 'VRTX', 'USB', 'ITW', 'FISV', 'HCA', 'SO',
        'NOC', 'ETN', 'EOG', 'BDX', 'UBER', 'CME', 'LRCX', 'BSX', 'CSX', 'GD', 'MU',
        'TFC', 'AON', 'MRNA', 'HUM', 'PNC', 'WM', 'MMM', 'APD', 'CL', 'ATVI', 'CHTR',
        'GM', 'ICE', 'FCX', 'SHW', 'MPC', 'EPD', 'SCCO', 'MET', 'BN', 'SHOP',
        'MELI', 'MCO', 'OXY', 'ORLY', 'MNST', 'SNPS', 'NTES', 'KLAC', 'MAR', 'FDX', 'CDNS',
        'NSC', 'F', 'PANW', 'DG', 'BIDU', 'KDP', 'MCK', 'VLO', 'SRE', 'PXD', 'SNOW',
        'AZO', 'VMW', 'HSY', 'KKR', 'KHC', 'D', 'NXPI', 'EMR', 'APH', 'EW',
        'WDAY', 'AEP', 'ADSK', 'FTNT', 'PSX', 'ECL', 'MCHP', 'PH', 'ROP', 'GIS',
        'CTAS', 'MSI', 'SQ', 'AIG', 'ADM', 'CMG', 'JCI', 'DXCM', 'CTVA', 'A', 'MSCI',
        'TEAM', 'AFL', 'NUE', 'TRV', 'KMB', 'LVS', 'EXC', 'LULU', 'COF', 'ANET', 'TT', 'STZ', 'HES',
        'TEL', 'RSG', 'BK', 'CNC', 'PAYX', 'FIS', 'IDXX', 'DOW', 'APO', 'IQV', 'LHX', 'TDG', 'BIIB',
        'AJG', 'SYY', 'KMI', 'ROST', 'ET', 'PCAR', 'ODFL', 'HLT', 'WMB', 'CARR', 'MRVL',
        'WBD', 'AMP', 'PRU', 'DD', 'XEL', 'YUM', 'GFS', 'SE', 'CMI', 'IBKR', 'NEM', 'LNG',
        'ALL', 'ON', 'MBLY', 'OTIS', 'MPLX', 'DVN', 'GWW', 'ROK', 'AME', 'BNTX', 'ILMN',
        'MTD', 'CTSH', 'KEYS', 'GEHC', 'ED', 'HAL', 'DLTR', 'ABC', 'CPRT', 'APTV',
        'DHI', 'URI', 'RMD', 'WBA', 'STT', 'LYB', 'CSGP', 'KR', 'GPN', 'PEG', 'PCG', 'BKR', 'EA',
        'PPG', 'FAST', 'DELL', 'SGEN', 'ALB', 'GLW', 'OKE', 'DFS', 'HPQ', 'TTD', 'GOLD', 'FERG',
        'WEC', 'CDW', 'NDAQ', 'LEN', 'CBRE', 'ENPH', 'ES', 'CPNG', 'VRSK', 'CEG',
        'MTB', 'ALNY', 'IT', 'AWK', 'ULTA', 'CRWD', 'TROW', 'VEEV', 'ZBH', 'TSCO', 'EBAY',
        'WTW', 'EFX', 'EIX', 'CCEP', 'GPC', 'DDOG', 'FITB', 'YUMC', 'HZNP', 'ACGL',
        'HRL', 'HIG', 'FANG', 'ALGN', 'VMC', 'IFF', 'DAL', 'RBLX', 'FTV', 'RJF', 'DASH',
        'SPOT', 'DTE', 'FRC', 'ANSS', 'MPWR', 'CQP', 'FE', 'K', 'IR', 'WST', 'MLM',
        'RPRX', 'NU', 'LH', 'TECK', 'AEE', 'RF', 'ETR', 'ZM', 'PWR', 'PFG', 'HBAN',
        'STLD', 'DOV', 'VRSN', 'TSN', 'PPL', 'NET', 'HEI', 'LUV', 'HPE', 'CFG', 'BAX', 'QSR',
        'TDY', 'PODD', 'BIP', 'CHD', 'HOLX', 'MKC', 'CAH', 'NTRS', 'BMRN', 'HUBS',
        'CINF', 'LPLA', 'JBHT', 'WAT', 'EPAM', 'XYL', 'BBY', 'WAB', 'PLTR', 'FOX', 'ZS', 'OMC',
        'TTWO', 'CLX', 'OWL', 'CHWY', 'STE', 'RCL', 'RIVN', 'GRMN', 'ICLR', 'CTRA', 'SWKS', 'CNP',
        'LCID', 'PAYC', 'IEP', 'BALL', 'CMS', 'SIRI', 'ROL', 'KEY', 'MKL', 'WRB', 'DRI', 'HWM',
        'EXPD', 'LYV', 'INCY', 'AES', 'FSLR', 'IEX', 'CAG', 'SIVB', 'MOH', 'SPLK', 'FICO',
        'RKT', 'WMG', 'UI', 'COO', 'SEDG', 'TW', 'MOS', 'AMCR', 'BR', 'DGX', 'PKI', 'ATO', 'TRGP',
        'MGM', 'EXPE', 'PINS', 'ZBRA', 'AVTR', 'FDS', 'TER', 'SNAP', 'BRO', 'ETSY', 'NVR', 'MRO',
        'UAL', 'CF', 'FMC', 'SJM', 'U', 'AGR', 'FLT', 'LKQ', 'CPB', 'BEN', 'CHKP', 'SYF', 'WLK',
        'SSNC', 'PARA', 'J', 'PTC', 'EDR', 'TXT', 'NIO', 'RE', 'AER', 'BURL', 'COIN', 'AVY',
        'MDB', 'POOL', 'BG', 'RS', 'NTAP', 'IPG', 'STX', 'BAM', 'LW', 'L', 'BIO', 'ARES',
        'TYL', 'EVRG', 'VTRS', 'NDSN', 'CCL', 'TME', 'LDOS', 'AZPN', 'TPL', 'LBRDA', 'CBOE', 'TRMB',
        'CSL', 'SWK', 'LNT', 'HUBB', 'AXON', 'GEN', 'CRBG', 'GRAB', 'SNA', 'IP', 'MKTX',
        'TRU', 'FHN', 'WDC', 'PKG', 'TWLO', 'DOCU', 'CE', 'CTLT', 'BAH', 'CG', 'ENTG',
        'CRL', 'DPZ', 'WSO', 'ACM', 'MAS', 'WYNN', 'DT', 'JKHY', 'PHM', 'APA', 'GGG',
        'GDDY', 'MTCH', 'H', 'AKAM', 'EQH', 'WTRG', 'BLDR', 'LSCC', 'GL', 'TECH', 'TTC', 'CHRW',
        'OKTA', 'BWA', 'BSY', 'CNA', 'FNF', 'FIVE', 'PCTY', 'UTHR', 'TFX', 'KMX', 'CDAY', 'PSNY',
        'DOX', 'UHAL', 'AFG', 'RPM', 'ACI', 'CZR', 'EXAS', 'TAP', 'HSIC', 'EQT', 'ERIE', 'JBL',
        'RYAN', 'PAG', 'NI', 'EWBC', 'FCNCA', 'SCI', 'NWS', 'SRPT', 'MMP', 'DKS', 'Z', 'QGEN',
        'TPG', 'BRKR', 'WSC', 'OVV', 'CHK', 'WES', 'FLEX', 'DECK', 'DAR', 'AAL', 'RGEN',
        'DINO', 'VFC', 'ALLE', 'TPR', 'CCK', 'RRX', 'ZI', 'EMN', 'AGCO', 'BAP', 'QRVO', 'AOS',
        'JNPR', 'CLF', 'LECO', 'MORN', 'BJ', 'PEN', 'BZ', 'FND', 'NBIX', 'ARMK', 'BKI', 'ROKU',
        'RGA', 'BILL', 'TOST', 'MTN', 'BBWI', 'LBTYA', 'UHS', 'KNX', 'WOLF', 'SNX', 'CMA', 'WBS',
        'LII','CAR', 'XM', 'COTY', 'AGL', 'PNR', 'PFGC', 'RNR', 'JAZZ', 'ALLY', 'PSTG', 'DKNG', 
        'CHDN','BILI', 'VST', 'HOOD', 'PAA', 'PLUG', 'MANH', 'OC', 'HII', 'PCOR', 'NVCR', 'AAP',
        'USFD','RHI','FFIV', 'JEF', 'G', 'WSM', 'DCP', 'MASI', 'OSH', 'PATH', 'WCC', 'ALGM',
        'UNM', 'NOV', 'IVZ','LEA', 'PNW', 'CFR', 'CBSH', 'VIPS', 'WEX', 'LEGN', 'MIDD', 'JLL',
        'CGNX', 'AA', 'WRK','SEIC','FBIN', 'IOT', 'UGI', 'HAS', 'IRDM', 'CROX', 'WAL', 'XPEV',
        'OLN', 'RL', 'CASY', 'ORI','GNRC','TX', 'RGLD', 'DLB', 'ST', 'WHR', 'NRG', 'NFE',
        'SBNY', 'DCI', 'INSP', 'AN', 'ALV', 'ITT','YMM','KNSL', 'NVT', 'XRAY', 'DBX', 'ZION',
        'OGE', 'TTEK', 'BERY', 'CHE', 'ATR', 'KBR', 'RH','WMS', 'DVA', 'NXST', 'MTZ', 'DISH',
        'SAIA', 'VOYA', 'ACHC', 'AR', 'CNXC', 'NCLH', 'LAD', 'TPX','CLH', 'SEE', 'CFLT', 'MHK',
        'CELH', 'GLOB', 'GPK', 'CLVT', 'SWAV', 'EME', 'ADT', 'ARW', 'XP','SF','CACI', 'CIEN',
        'HOG', 'BOKF', 'LEVI', 'AIZ', 'TXRH', 'MTDR', 'UWMC', 'DDS', 'VMI', 'PLNT', 'SKX', 'BYD',
        'MNDY', 'EDU', 'RBC', 'SITE', 'FYBR', 'ONON', 'PB', 'PII', 'NATI', 'GTLB','HESM',
        'MAT', 'KRTX', 'SGFY', 'HALO', 'CR', 'HLI', 'GNTX', 'GME', 'CMC', 'NYT', 'WH', 'CW', 'LFUS',
        'THC','OGN', 'BLCO', 'LSTR', 'FUTU', 'IQ', 'CWEN', 'WWE', 'DXC', 'CHH', 'DOCS', 'ROIV',
        'ASND','NTNX','INGR', 'AXTA', 'AMKR', 'ELAN', 'MEDP', 'MDU', 'NYCB', 'IPGP', 'BLD', 'X',
        'BC', 'MKSI','TOL','CPRI', 'BROS', 'PRI', 'AYI', 'AMG', 'SNV', 'TKR', 'NVST', 'HTZ', 'EHC',
        'OLED', 'ALK', 'FTI','COHR','VLY', 'SSB', 'FAF', 'NEP', 'AQUA', 'CHX', 'SIGI', 'NWL',
        'MUR', 'SOFI', 'APLS', 'RLI', 'HXL', 'VRT', 'WWD', 'VAC', 'COUP', 'M', 'QDEL', 'GMED',
        'LNW', 'CACC', 'PNFP', 'FLO', 'VVV','GWRE','WTS', 'OSK', 'SON', 'CYBR', 'MUSA', 'HRB',
        'SAIC', 'GXO', 'SLGN', 'INFA', 'REYN', 'HCP','TREX','TXG', 'HUN', 'PPC', 'RCM', 'NOVT',
        'PBF', 'MP', 'PDCE', 'ATKR', 'ESTC', 'RXDX', 'LNC','CRUS','SLAB', 'SMAR', 'CCCS', 'FIVN',
        'EXEL', 'UNVR', 'RRC', 'COLM', 'FCN', 'EXLS', 'LU', 'CNM','WTFC','STVN', 'NE', 'ASH',
        'UBSI', 'MLCO', 'HQY', 'AIT', 'ENLC', 'FSK', 'APP', 'OZK', 'VAL', 'W','IAA', 'CHRD', 'BWXT',
        'EXPO', 'MSA', 'SWN', 'IONS', 'SPSC', 'EEFT', 'TNET', 'FFIN', 'NTRA','POST','LANC', 'HGV',
        'IGT', 'OMF', 'RUN', 'UFPI', 'CIVI', 'ABG', 'OPCH', 'NFG', 'IDA', 'WU','ATI','ALIT', 'DNB',
        'AXS', 'BPOP', 'ONB', 'CERE', 'APG', 'LHCG', 'FNB', 'PVH', 'GBCI', 'FLR','CC', 'NEWR',
        'ORCC','WING', 'MDGL', 'FOXF', 'EXP', 'ORA', 'BEPC', 'SRCL', 'SNDR', 'MMS', 'THO','ENSG',
        'AM','THG', 'SHC', 'EVR', 'CADE', 'RIG', 'APPF', 'WIX', 'DTM', 'GPS', 'PENN','NJR',
        'HOMB', 'VNOM', 'COKE', 'R', 'SMCI', 'TENB', 'PRGO', 'ASO', 'WEN', 'ESI', 'TDOC', 'MSM',
        'GTLS','ITCI','TAL', 'GATX', 'PAGS','JHG', 'PYCR', 'LEG', 'YOU', 'CYTK', 'AVNT',
        'SMG', 'RRR', 'SYNA', 'MTSI', 'DRVN', 'IART', 'BIPC', 'FOUR', 'AL', 'NSP', 'RMBS',
        'SSD', 'PWSC', 'PTON', 'POWI', 'ESNT', 'PSN', 'FLS', 'DAVA', 'BOX', 'IAC', 'AYX', 'SUN',
        'LPX', 'SEB', 'WK', 'MSGS', 'HE', 'DLO', 'FRHC', 'ALKS', 'ASGN', 'BFAM', 'AB', 'VC',
        'BE', 'ALSN', 'FIX', 'CWAN', 'FRSH', 'TGNA', 'AJRD', 'DV', 'FN', 'S', 'QLYS', 'CBT',
        'QS','OGS','LTHM','ADNT','BRBR','LYFT','BECN','SR','AZEK','ARWR','ASB','BMI','ENOV',
        'FELE', 'TSEM', 'MAN', 'WFRD', 'ALTR', 'MGY', 'ATHM', 'BCPC', 'POR', 'HP', 'UMBF',
        'NSIT', 'MODG', 'NEOG', 'UA', 'HHC', 'KEX', 'CABO', 'SWX', 'HWC', 'HLNE', 'HRI', 'ESGR',
        'SHLS', 'FIZZ', 'XPO', 'ATCO', 'ICUI', 'MANU', 'BL', 'BMBL', 'BKH', 'DIOD', 'AAON',
        'LAZ', 'AVT', 'MLI', 'PNM', 'FCFS', 'TDC', 'SEAS', 'KMPR', 'CHPT', 'MTG', 'DNLI', 'WNS',
        'FL', 'GLBE', 'ZWS', 'JXN', 'LNTH', 'HAE', 'SGRY', 'BHF', 'SKY', 'DEN', 'UMPQ', 'SYNH',
        'BTU', 'LUMN', 'VNT', 'TFSL', 'SAM', 'SFBS', 'AIMC', 'AMN', 'ACT', 'ACLS', 'GTES', 'WTM',
        'MTH', 'CWST', 'CRSP', 'LITE', 'MMSI', 'KNTK', 'PINC', 'PEGA', 'ONTO', 'WHD', 'ELF', 'ZD',
        'FOCS', 'TMHC', 'FIBK', 'FUL', 'AEL', 'QFIN', 'CVT', 'BDC', 'MAXR', 'TRTN', 'UCBI',
        'SEM', 'FRO', 'AFRM', 'LIFW', 'INST', 'IPAR', 'AGO', 'SMPL', 'MRVI', 'SPR', 'KD', 'FOLD',
        'ENS', 'SM', 'AWI', 'STNG', 'SANM', 'SRAD', 'INDB', 'NCR', 'CPA', 'DUOL', 'WIRE', 'LOPE',
        'GEF', 'KWR', 'SLM', 'AEIS', 'STR', 'SUM', 'CNS', 'UNF', 'OLLI', 'AMBA', 'ENV', 'YETI',
        'KSS', 'JBT', 'PLTK', 'RUM', 'OLPX', 'FLNC', 'FHI', 'GOLF', 'RNG', 'ALE', 'RDN', 'LTH',
        'ESAB', 'NNI', 'SFM', 'NWE', 'PCVX', 'JWN', 'AWR', 'ESMT', 'SIG', 'FHB', 'NTLA', 'CALX',
        'VIR', 'VIRT', 'DRS', 'TNL', 'RARE', 'KOS', 'AIN', 'GPI', 'CVBF', 'DOCN', 'PI', 'OI', 'NEU',
        'MSTR', 'AMC', 'IRTC', 'ABCB', 'NGVT', 'STAA', 'DNA', 'BRP', 'VSCO', 'PTCT', 'PZZA', 'SPT',
        'EVH','GHC','FSS', 'MQ','WSFS','PSEC', 'ARRY', 'PTEN', 'BCO', 'GH','CD', 'SFNC', 'CRK',
        'GT', 'APPN', 'AMBP', 'CWT', 'SPXC', 'PACW', 'ASAN', 'NWTN', 'RUSHA', 'ALVO', 'HI', 'ACDC',
        'GBTG', 'ONEM', 'CBU', 'EVOP', 'CCOI', 'CATY', 'SXT', 'COOP', 'TIGO', 'BSM', 'EYE', 'ZGN',
        'FRPT', 'PFSI', 'CVI', 'HUBG', 'AZTA', 'PRVA', 'HGTY', 'PPBI', 'ABM', 'TCBI', 'TR', 'STEP',
        'LAC', 'SQSP', 'NCNO', 'MC', 'AMED', 'CRVL', 'CWK', 'DQ', 'HL', 'IBP', 'ACAD', 'MRCY',
        'PGNY', 'ATAT', 'BLKB', 'MAIN', 'GNW', 'TWKS', 'TRIP', 'INMD', 'CERT', 'NOMD', 'HPK',
        'PBH', 'WD', 'DORM', 'BEAM', 'BOH', 'KLIC', 'WOR', 'TWNK', 'VSH', 'KFY', 'BRZE', 'AX', 
        'AVA', 'NARI', 'CALM', 'CNMD', 'IMCR', 'AHCO', 'KBH', 'LIVN', 'EVA', 'AMTD', 'WERN', 'LCII',
        'CRI', 'OTTR', 'AY', 'BANF', 'BCC', 'RPD', 'ISEE', 'VRNS', 'MCW', 'HRMY', 'ACIW', 'AEO',
        'FULT', 'CRC', 'CNO', 'STNE', 'REZI', 'SSRM', 'MXL', 'AXSM', 'AAWW', 'GO', 'WOOF', 'ARCH',
        'IBOC', 'RLX', 'AMRC', 'IOSP', 'FWRD', 'AUB', 'CXM', 'AXNX', 'BKU', 'SPWR', 'ACA', 'APAM',
        'PR', 'ETRN', 'ROG', 'HELE', 'MMYT', 'PDCO', 'INSM', 'JBLU', 'PIPR', 'MRTX', 'RVNC', 'CVLT',
        'PLXS', 'CEQP', 'CNX', 'URBN', 'UNFI', 'ESE', 'RKLB', 'EXTR','LESL', 'DY', 'FFBC', 'SMR',
        'HSAI', 'BPMC', 'HAYW', 'EBC', 'JOBY', 'PRTA', 'DADA', 'ABCL', 'PD', 'JJSF', 'THS', 'OLK',
        'SSTK', 'SHOO', 'ARLP', 'MDC', 'SAGE', 'FG', 'AMR', 'DAN', 'VICR', 'PROK', 'FBP', 'TNDM',
        'JOE', 'LGIH', 'ZIM', 'IFS', 'LBRT', 'ALRM', 'MATX', 'BRC', 'SONO', 'ZIP', 'MYOV', 'TGTX',
        'NVMI', 'FLYW', 'XRX', 'MGRC', 'MGEE', 'PAGP', 'SITM', 'VSAT', 'ENR', 'BOWL', 'ITRI', 'SPB',
        'PRFT', 'DCT', 'KAI', 'PACB', 'AI', 'GMS', 'JKS', 'CBZ', 'VVNT', 'GETY', 'KTB', 'VRNT',
        'ITGR', 'WLY', 'FRME', 'IBTX', 'NAVI', 'JAMF', 'VTYX', 'PRGS', 'VIAV', 'CSIQ', 'ARCB',
        'NPO', 'NOG', 'COLB', 'INTA', 'CVCO', 'AGTI', 'IHS', 'GKOS', 'AMLX', 'CBRL', 'RXO', 'LAZR',
        'FTAI', 'KW', 'ARNC', 'FUN', 'PAX', 'CRS', 'ULCC', 'FORM', 'THRM', 'TROX', 'CORT', 'BOOT',
        'BLMN', 'WAFD', 'OMCL', 'GLNG', 'XENE', 'SIMO', 'ODP', 'IMVT', 'WDFC', 'VRRM', 'TRUP',
        'SBCF', 'SCL', 'SIX', 'SJW', 'YY', 'TTEC', 'HEP', 'WEBR', 'GBDC', 'KMT', 'FROG', 'EE',
        'SHAK', 'NUVA', 'FTDR', 'EVTC', 'TRN', 'VERX', 'UTZ', 'STRA', 'MTRN', 'VCTR', 'EPC', 'RVMD',
        'CLBK', 'PSMT', 'XPRO', 'EXPI', 'HTH', 'TPH', 'RNW', 'WMK', 'GFF', 'FGEN', 'HLIO', 'TOWN',
        'CENT', 'GSAT', 'RLAY', 'NEX', 'USM', 'XPEL', 'VGR', 'WSBC', 'CPE', 'TALO', 'SBLK', 'HTGC',
        'AVAV', 'MWA', 'IDCC', 'BANR', 'DNUT', 'SAH', 'INSW', 'CSWI', 'CPK']
